In [1]:
import pandas as pd

In [3]:
from google.colab import files
uploaded = files.upload()

Saving twitter_dataset.csv to twitter_dataset.csv

In [4]:
df = pd.read_csv("twitter_dataset.csv")
print(df)

                    created_at             tweet_id receiver_name receiver_id  \
0    2022-04-25 17:10:41+00:00  1518638641848803329           NaN         NaN
1    2022-04-25 17:10:38+00:00  1518638627923894274           NaN         NaN
2    2022-04-25 17:10:37+00:00  1518638624849412096           NaN         NaN
3    2022-04-25 17:10:24+00:00  1518638571049078784           NaN         NaN
4    2022-04-25 17:10:09+00:00  1518638508201881600           NaN         NaN
..                         ...                  ...           ...         ...
497  2022-04-25 17:56:23+00:00  1518650142198534148           NaN         NaN
498  2022-04-25 17:56:23+00:00  1518650141535789062           NaN         NaN
499  2022-04-25 17:56:23+00:00  1518650141338652673           NaN         NaN
500  2022-04-25 17:56:23+00:00  1518650140579487745           NaN         NaN
501  2022-04-25 17:56:21+00:00  1518650134384750592           NaN         NaN

                                            tweet_text      screen_name  \
0    RT @WCKitchen: Scenes from our food kit delive...      joelleshay1
1    Public health experts, Juno Thomas and Linda E...         SABCNews
2    RT @_Bonga: KZN revised the cost of the floods...           _RebaS
3    MDMEMA: Even if you don’t live next to a water...  BlueCrabsFoodFe
4    RT @AmyDoghouse: @elonmusk @JohnnaCrider1 @sta...  albertw73935497
..                                                 ...              ...
497  RT @ape_apeee: y’all don’t be having no legiti...  dasjathaprinces
498  RT @NossaProm0: Cupom Shoptime 🧡\n\nDeuses &am...      bl4ck_bitch
499  This bitch better find herself before I tell h...         __Kayy20
500  RT @SkyeAsiyanbi: Omg I really can’t stand a c...    AmayaNicolee_
501    RT @1future: Bitch i will blow dis 💰 Ain stingy     JTMon3ybeatz

                                 name           account_creation_date  \
0                        @Joellimoguy  Fri Mar 31 05:40:07 +0000 2017
1                           SABC News  Wed Mar 18 15:16:33 +0000 2009
2                                Reba  Sun Nov 23 15:31:45 +0000 2014
3    Blue Crabs Beer Food & Wine Fest  Fri Feb 16 20:37:12 +0000 2018
4                   Albert J. Wallace  Mon May 11 12:41:54 +0000 2020
..                                ...                             ...
497                                 💕  Mon Apr 04 04:42:29 +0000 2016
498                    𝑰'𝒎 𝑺𝒂𝒃𝒓𝒊𝒏𝒂 •🪄  Fri Apr 08 15:34:16 +0000 2022
499                           Kaykay💕  Mon Jul 19 18:33:39 +0000 2021
500                         Uh•My•Uh🍯  Tue Jun 12 18:50:49 +0000 2018
501                       JT The Goat  Wed Apr 23 00:45:27 +0000 2014

                                                  urls
0                                                   []
1    [{'url': 'https://t.co/EE5xDNmv7q', 'expanded_...
2                                                   []
3    [{'url': 'https://t.co/qZkYMJ183I', 'expanded_...
4                                                   []
..                                                 ...
497                                                 []
498                                                 []
499                                                 []
500                                                 []
501                                                 []

[502 rows x 9 columns]

In [5]:
df.head()

,created_at,tweet_id,receiver_name,receiver_id,tweet_text,screen_name,name,account_creation_date,urls
0,2022-04-25 17:10:41+00:00,1518638641848803329,NaN,NaN,RT @WCKitchen: Scenes from our food kit delive...,joelleshay1,@Joellimoguy,Fri Mar 31 05:40:07 +0000 2017,[]
1,2022-04-25 17:10:38+00:00,1518638627923894274,NaN,NaN,"Public health experts, Juno Thomas and Linda E...",SABCNews,SABC News,Wed Mar 18 15:16:33 +0000 2009,"[{'url': 'https://t.co/EE5xDNmv7q', 'expanded_..."
2,2022-04-25 17:10:37+00:00,1518638624849412096,NaN,NaN,RT @_Bonga: KZN revised the cost of the floods...,_RebaS,Reba,Sun Nov 23 15:31:45 +0000 2014,[]
3,2022-04-25 17:10:24+00:00,1518638571049078784,NaN,NaN,MDMEMA: Even if you don’t live next to a water...,BlueCrabsFoodFe,Blue Crabs Beer Food & Wine Fest,Fri Feb 16 20:37:12 +0000 2018,"[{'url': 'https://t.co/qZkYMJ183I', 'expanded_..."
4,2022-04-25 17:10:09+00:00,1518638508201881600,NaN,NaN,RT @AmyDoghouse: @elonmusk @JohnnaCrider1 @sta...,albertw73935497,Albert J. Wallace,Mon May 11 12:41:54 +0000 2020,[]

In [7]:
df_clean = pd.read_csv("twitter_dataset.csv")

In [8]:
df_clean['tweet_text'] = df.tweet_text.str.lower()

In [9]:
df_clean.head()

,created_at,tweet_id,receiver_name,receiver_id,tweet_text,screen_name,name,account_creation_date,urls
0,2022-04-25 17:10:41+00:00,1518638641848803329,NaN,NaN,rt @wckitchen: scenes from our food kit delive...,joelleshay1,@Joellimoguy,Fri Mar 31 05:40:07 +0000 2017,[]
1,2022-04-25 17:10:38+00:00,1518638627923894274,NaN,NaN,"public health experts, juno thomas and linda e...",SABCNews,SABC News,Wed Mar 18 15:16:33 +0000 2009,"[{'url': 'https://t.co/EE5xDNmv7q', 'expanded_..."
2,2022-04-25 17:10:37+00:00,1518638624849412096,NaN,NaN,rt @_bonga: kzn revised the cost of the floods...,_RebaS,Reba,Sun Nov 23 15:31:45 +0000 2014,[]
3,2022-04-25 17:10:24+00:00,1518638571049078784,NaN,NaN,mdmema: even if you don’t live next to a water...,BlueCrabsFoodFe,Blue Crabs Beer Food & Wine Fest,Fri Feb 16 20:37:12 +0000 2018,"[{'url': 'https://t.co/qZkYMJ183I', 'expanded_..."
4,2022-04-25 17:10:09+00:00,1518638508201881600,NaN,NaN,rt @amydoghouse: @elonmusk @johnnacrider1 @sta...,albertw73935497,Albert J. Wallace,Mon May 11 12:41:54 +0000 2020,[]

In [12]:
import re
re.compile('<title>(.*)</title>')

re.compile(r'<title>(.*)</title>', re.UNICODE)

In [13]:
df_clean.tweet_text = df_clean.tweet_text.apply(lambda x: re.sub(r'https?:\/\/\S+', '', x))

In [14]:
df_clean.tweet_text.apply(lambda x: re.sub(r"www\.[a-z]?\.?(com)+|[a-z]+\.(com)", '', x))

0      rt @wckitchen: scenes from our food kit delive...
1      public health experts, juno thomas and linda e...
2      rt @_bonga: kzn revised the cost of the floods...
3      mdmema: even if you don’t live next to a water...
4      rt @amydoghouse: @elonmusk @johnnacrider1 @sta...
                             ...
497    rt @ape_apeee: y’all don’t be having no legiti...
498    rt @nossaprom0: cupom shoptime 🧡\n\ndeuses &am...
499    this bitch better find herself before i tell h...
500    rt @skyeasiyanbi: omg i really can’t stand a c...
501      rt @1future: bitch i will blow dis 💰 ain stingy
Name: tweet_text, Length: 502, dtype: object

In [15]:
df_clean.head()

,created_at,tweet_id,receiver_name,receiver_id,tweet_text,screen_name,name,account_creation_date,urls
0,2022-04-25 17:10:41+00:00,1518638641848803329,NaN,NaN,rt @wckitchen: scenes from our food kit delive...,joelleshay1,@Joellimoguy,Fri Mar 31 05:40:07 +0000 2017,[]
1,2022-04-25 17:10:38+00:00,1518638627923894274,NaN,NaN,"public health experts, juno thomas and linda e...",SABCNews,SABC News,Wed Mar 18 15:16:33 +0000 2009,"[{'url': 'https://t.co/EE5xDNmv7q', 'expanded_..."
2,2022-04-25 17:10:37+00:00,1518638624849412096,NaN,NaN,rt @_bonga: kzn revised the cost of the floods...,_RebaS,Reba,Sun Nov 23 15:31:45 +0000 2014,[]
3,2022-04-25 17:10:24+00:00,1518638571049078784,NaN,NaN,mdmema: even if you don’t live next to a water...,BlueCrabsFoodFe,Blue Crabs Beer Food & Wine Fest,Fri Feb 16 20:37:12 +0000 2018,"[{'url': 'https://t.co/qZkYMJ183I', 'expanded_..."
4,2022-04-25 17:10:09+00:00,1518638508201881600,NaN,NaN,rt @amydoghouse: @elonmusk @johnnacrider1 @sta...,albertw73935497,Albert J. Wallace,Mon May 11 12:41:54 +0000 2020,[]

In [16]:
df_clean.tweet_text = df_clean.tweet_text.apply(lambda x: re.sub(r'{link}', '', x))
df_clean.tweet_text = df_clean.tweet_text.apply(lambda x: re.sub(r"\[video\]", '', x))

In [17]:
df_clean.tweet_text = df_clean.tweet_text.apply(lambda x: re.sub(r'&[a-z]+;', '', x))

In [18]:
df_clean.tweet_text = df_clean.tweet_text.apply(lambda x: re.sub(r"[^a-z\s\(\-:\)\\\/\];='#]", '', x))

In [19]:
df_clean.head()

,created_at,tweet_id,receiver_name,receiver_id,tweet_text,screen_name,name,account_creation_date,urls
0,2022-04-25 17:10:41+00:00,1518638641848803329,NaN,NaN,rt wckitchen: scenes from our food kit deliver...,joelleshay1,@Joellimoguy,Fri Mar 31 05:40:07 +0000 2017,[]
1,2022-04-25 17:10:38+00:00,1518638627923894274,NaN,NaN,public health experts juno thomas and linda er...,SABCNews,SABC News,Wed Mar 18 15:16:33 +0000 2009,"[{'url': 'https://t.co/EE5xDNmv7q', 'expanded_..."
2,2022-04-25 17:10:37+00:00,1518638624849412096,NaN,NaN,rt bonga: kzn revised the cost of the floods f...,_RebaS,Reba,Sun Nov 23 15:31:45 +0000 2014,[]
3,2022-04-25 17:10:24+00:00,1518638571049078784,NaN,NaN,mdmema: even if you dont live next to a water ...,BlueCrabsFoodFe,Blue Crabs Beer Food & Wine Fest,Fri Feb 16 20:37:12 +0000 2018,"[{'url': 'https://t.co/qZkYMJ183I', 'expanded_..."
4,2022-04-25 17:10:09+00:00,1518638508201881600,NaN,NaN,rt amydoghouse: elonmusk johnnacrider statsfee...,albertw73935497,Albert J. Wallace,Mon May 11 12:41:54 +0000 2020,[]

In [20]:
from nltk.tokenize import TweetTokenizer
tknzr = TweetTokenizer()
df_clean['tokens'] = df_clean['tweet_text'].apply(tknzr.tokenize)

In [21]:
df_clean.head()

,created_at,tweet_id,receiver_name,receiver_id,tweet_text,screen_name,name,account_creation_date,urls,tokens
0,2022-04-25 17:10:41+00:00,1518638641848803329,NaN,NaN,rt wckitchen: scenes from our food kit deliver...,joelleshay1,@Joellimoguy,Fri Mar 31 05:40:07 +0000 2017,[],"[rt, wckitchen, :, scenes, from, our, food, ki..."
1,2022-04-25 17:10:38+00:00,1518638627923894274,NaN,NaN,public health experts juno thomas and linda er...,SABCNews,SABC News,Wed Mar 18 15:16:33 +0000 2009,"[{'url': 'https://t.co/EE5xDNmv7q', 'expanded_...","[public, health, experts, juno, thomas, and, l..."
2,2022-04-25 17:10:37+00:00,1518638624849412096,NaN,NaN,rt bonga: kzn revised the cost of the floods f...,_RebaS,Reba,Sun Nov 23 15:31:45 +0000 2014,[],"[rt, bonga, :, kzn, revised, the, cost, of, th..."
3,2022-04-25 17:10:24+00:00,1518638571049078784,NaN,NaN,mdmema: even if you dont live next to a water ...,BlueCrabsFoodFe,Blue Crabs Beer Food & Wine Fest,Fri Feb 16 20:37:12 +0000 2018,"[{'url': 'https://t.co/qZkYMJ183I', 'expanded_...","[mdmema, :, even, if, you, dont, live, next, t..."
4,2022-04-25 17:10:09+00:00,1518638508201881600,NaN,NaN,rt amydoghouse: elonmusk johnnacrider statsfee...,albertw73935497,Albert J. Wallace,Mon May 11 12:41:54 +0000 2020,[],"[rt, amydoghouse, :, elonmusk, johnnacrider, s..."

In [22]:
print(df_clean)

                    created_at             tweet_id receiver_name receiver_id  \
0    2022-04-25 17:10:41+00:00  1518638641848803329           NaN         NaN
1    2022-04-25 17:10:38+00:00  1518638627923894274           NaN         NaN
2    2022-04-25 17:10:37+00:00  1518638624849412096           NaN         NaN
3    2022-04-25 17:10:24+00:00  1518638571049078784           NaN         NaN
4    2022-04-25 17:10:09+00:00  1518638508201881600           NaN         NaN
..                         ...                  ...           ...         ...
497  2022-04-25 17:56:23+00:00  1518650142198534148           NaN         NaN
498  2022-04-25 17:56:23+00:00  1518650141535789062           NaN         NaN
499  2022-04-25 17:56:23+00:00  1518650141338652673           NaN         NaN
500  2022-04-25 17:56:23+00:00  1518650140579487745           NaN         NaN
501  2022-04-25 17:56:21+00:00  1518650134384750592           NaN         NaN

                                            tweet_text      screen_name  \
0    rt wckitchen: scenes from our food kit deliver...      joelleshay1
1    public health experts juno thomas and linda er...         SABCNews
2    rt bonga: kzn revised the cost of the floods f...           _RebaS
3    mdmema: even if you dont live next to a water ...  BlueCrabsFoodFe
4    rt amydoghouse: elonmusk johnnacrider statsfee...  albertw73935497
..                                                 ...              ...
497  rt apeapeee: yall dont be having no legitimate...  dasjathaprinces
498  rt nossaprom: cupom shoptime \n\ndeuses  monst...      bl4ck_bitch
499  this bitch better find herself before i tell h...         __Kayy20
500  rt skyeasiyanbi: omg i really cant stand a cap...    AmayaNicolee_
501       rt future: bitch i will blow dis  ain stingy     JTMon3ybeatz

                                 name           account_creation_date  \
0                        @Joellimoguy  Fri Mar 31 05:40:07 +0000 2017
1                           SABC News  Wed Mar 18 15:16:33 +0000 2009
2                                Reba  Sun Nov 23 15:31:45 +0000 2014
3    Blue Crabs Beer Food & Wine Fest  Fri Feb 16 20:37:12 +0000 2018
4                   Albert J. Wallace  Mon May 11 12:41:54 +0000 2020
..                                ...                             ...
497                                 💕  Mon Apr 04 04:42:29 +0000 2016
498                    𝑰'𝒎 𝑺𝒂𝒃𝒓𝒊𝒏𝒂 •🪄  Fri Apr 08 15:34:16 +0000 2022
499                           Kaykay💕  Mon Jul 19 18:33:39 +0000 2021
500                         Uh•My•Uh🍯  Tue Jun 12 18:50:49 +0000 2018
501                       JT The Goat  Wed Apr 23 00:45:27 +0000 2014

                                                  urls  \
0                                                   []
1    [{'url': 'https://t.co/EE5xDNmv7q', 'expanded_...
2                                                   []
3    [{'url': 'https://t.co/qZkYMJ183I', 'expanded_...
4                                                   []
..                                                 ...
497                                                 []
498                                                 []
499                                                 []
500                                                 []
501                                                 []

                                                tokens
0    [rt, wckitchen, :, scenes, from, our, food, ki...
1    [public, health, experts, juno, thomas, and, l...
2    [rt, bonga, :, kzn, revised, the, cost, of, th...
3    [mdmema, :, even, if, you, dont, live, next, t...
4    [rt, amydoghouse, :, elonmusk, johnnacrider, s...
..                                                 ...
497  [rt, apeapeee, :, yall, dont, be, having, no, ...
498  [rt, nossaprom, :, cupom, shoptime, deuses, mo...
499  [this, bitch, better, find, herself, before, i...
500  [rt, skyeasiyanbi, :, omg, i, really, cant, st...
501  [rt, future, :, bitch, i, will, blow, dis, ain...

[502 rows x 10 columns]

In [24]:
import string

In [25]:
PUNCTUATION_LIST = list(string.punctuation)
def remove_punctuation(word_list):
    """Remove punctuation tokens from a list of tokens"""
    return [w for w in word_list if w not in PUNCTUATION_LIST]
df_clean['tokens'] = df_clean['tokens'].apply(remove_punctuation)

In [26]:
df_clean.head()

,created_at,tweet_id,receiver_name,receiver_id,tweet_text,screen_name,name,account_creation_date,urls,tokens
0,2022-04-25 17:10:41+00:00,1518638641848803329,NaN,NaN,rt wckitchen: scenes from our food kit deliver...,joelleshay1,@Joellimoguy,Fri Mar 31 05:40:07 +0000 2017,[],"[rt, wckitchen, scenes, from, our, food, kit, ..."
1,2022-04-25 17:10:38+00:00,1518638627923894274,NaN,NaN,public health experts juno thomas and linda er...,SABCNews,SABC News,Wed Mar 18 15:16:33 +0000 2009,"[{'url': 'https://t.co/EE5xDNmv7q', 'expanded_...","[public, health, experts, juno, thomas, and, l..."
2,2022-04-25 17:10:37+00:00,1518638624849412096,NaN,NaN,rt bonga: kzn revised the cost of the floods f...,_RebaS,Reba,Sun Nov 23 15:31:45 +0000 2014,[],"[rt, bonga, kzn, revised, the, cost, of, the, ..."
3,2022-04-25 17:10:24+00:00,1518638571049078784,NaN,NaN,mdmema: even if you dont live next to a water ...,BlueCrabsFoodFe,Blue Crabs Beer Food & Wine Fest,Fri Feb 16 20:37:12 +0000 2018,"[{'url': 'https://t.co/qZkYMJ183I', 'expanded_...","[mdmema, even, if, you, dont, live, next, to, ..."
4,2022-04-25 17:10:09+00:00,1518638508201881600,NaN,NaN,rt amydoghouse: elonmusk johnnacrider statsfee...,albertw73935497,Albert J. Wallace,Mon May 11 12:41:54 +0000 2020,[],"[rt, amydoghouse, elonmusk, johnnacrider, stat..."

In [30]:
from google.colab import files
files.download("twitter_dataset.csv")

In [31]:
df_clean.to_csv("dataset.csv")

In [32]:
from google.colab import files
files.download("dataset.csv")